//! Interrupt descriptor table, trap frames and interrupt dispatch.
//!
//! The 256 entry stubs are generated by `build.rs` (one 16-byte stub per
//! vector) and funnel into `isr_common`, which saves the general purpose
//! registers and calls `interrupt_dispatch` with a pointer to the frame.

#![allow(dead_code)]

use core::arch::{asm, global_asm};
use core::sync::atomic::{AtomicU8, AtomicUsize, Ordering};

use crate::arch::{apic, cpu};

global_asm!(include_str!(concat!(env!("OUT_DIR"), "/isr_stubs.s")));

extern "C" {
    static isr_stubs: [u8; 0];
}

pub const VEC_TIMER: u8 = 32;
pub const VEC_FIRST_FREE: u8 = 48;
pub const VEC_SPURIOUS: u8 = 0xFF;

/// Saved register state at interrupt entry.  Field order matches the pushes
/// in `isr_common`.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct TrapFrame {
    pub r15: u64,
    pub r14: u64,
    pub r13: u64,
    pub r12: u64,
    pub r11: u64,
    pub r10: u64,
    pub r9: u64,
    pub r8: u64,
    pub rdi: u64,
    pub rsi: u64,
    pub rbp: u64,
    pub rbx: u64,
    pub rdx: u64,
    pub rcx: u64,
    pub rax: u64,
    pub vector: u64,
    pub error_code: u64,
    pub rip: u64,
    pub cs: u64,
    pub rflags: u64,
    pub rsp: u64,
    pub ss: u64,
}

pub type Handler = fn(&mut TrapFrame);

#[repr(C, packed)]
#[derive(Clone, Copy)]
struct Gate {
    offset_lo: u16,
    selector: u16,
    ist: u8,
    attr: u8,
    offset_mid: u16,
    offset_hi: u32,
    zero: u32,
}

const EMPTY_GATE: Gate = Gate { offset_lo: 0, selector: 0, ist: 0, attr: 0, offset_mid: 0, offset_hi: 0, zero: 0 };

#[repr(C, packed)]
struct DescriptorTablePointer {
    limit: u16,
    base: u64,
}

static mut IDT: [Gate; 256] = [EMPTY_GATE; 256];

const NO_HANDLER: usize = 0;
static HANDLERS: [AtomicUsize; 256] = [const { AtomicUsize::new(NO_HANDLER) }; 256];
static NEXT_VECTOR: AtomicU8 = AtomicU8::new(VEC_FIRST_FREE);
static SPURIOUS_COUNT: AtomicUsize = AtomicUsize::new(0);

fn gate(handler: u64, ist: u8) -> Gate {
    Gate {
        offset_lo: handler as u16,
        selector: crate::arch::gdt::KERNEL_CODE,
        ist,
        attr: 0x8E, // present, DPL 0, 64-bit interrupt gate
        offset_mid: (handler >> 16) as u16,
        offset_hi: (handler >> 32) as u32,
        zero: 0,
    }
}

pub fn init() {
    let base = core::ptr::addr_of!(isr_stubs) as u64;
    unsafe {
        let idt = &mut *core::ptr::addr_of_mut!(IDT);
        for v in 0..256usize {
            let ist = match v {
                8 => 1,  // #DF
                2 => 2,  // NMI
                18 => 3, // #MC
                _ => 0,
            };
            idt[v] = gate(base + 16 * v as u64, ist);
        }
        let ptr = DescriptorTablePointer {
            limit: (core::mem::size_of::<[Gate; 256]>() - 1) as u16,
            base: core::ptr::addr_of!(IDT) as u64,
        };
        asm!("lidt [{}]", in(reg) &ptr, options(nostack, preserves_flags));
    }
}

/// Register a handler for an external interrupt vector (>= 32).
pub fn register_handler(vector: u8, handler: Handler) {
    HANDLERS[vector as usize].store(handler as usize, Ordering::Release);
}

/// Allocate a fresh interrupt vector for a device.
pub fn alloc_vector() -> u8 {
    let v = NEXT_VECTOR.fetch_add(1, Ordering::Relaxed);
    assert!(v < 0xF0, "out of interrupt vectors");
    v
}

pub fn spurious_count() -> usize {
    SPURIOUS_COUNT.load(Ordering::Relaxed)
}

const EXCEPTION_NAMES: [&str; 32] = [
    "#DE divide error",
    "#DB debug",
    "NMI",
    "#BP breakpoint",
    "#OF overflow",
    "#BR bound range",
    "#UD invalid opcode",
    "#NM device not available",
    "#DF double fault",
    "coprocessor segment overrun",
    "#TS invalid TSS",
    "#NP segment not present",
    "#SS stack fault",
    "#GP general protection",
    "#PF page fault",
    "reserved",
    "#MF x87 floating point",
    "#AC alignment check",
    "#MC machine check",
    "#XM SIMD floating point",
    "#VE virtualisation",
    "#CP control protection",
    "reserved",
    "reserved",
    "reserved",
    "reserved",
    "reserved",
    "reserved",
    "#HV hypervisor injection",
    "#VC VMM communication",
    "#SX security",
    "reserved",
];

fn dump_frame(f: &TrapFrame) {
    crate::println!(
        "  rip={:#018x} cs={:#x} rflags={:#x} rsp={:#018x} ss={:#x}",
        f.rip, f.cs, f.rflags, f.rsp, f.ss
    );
    crate::println!("  rax={:#018x} rbx={:#018x} rcx={:#018x} rdx={:#018x}", f.rax, f.rbx, f.rcx, f.rdx);
    crate::println!("  rsi={:#018x} rdi={:#018x} rbp={:#018x} r8 ={:#018x}", f.rsi, f.rdi, f.rbp, f.r8);
    crate::println!("  r9 ={:#018x} r10={:#018x} r11={:#018x} r12={:#018x}", f.r9, f.r10, f.r11, f.r12);
    crate::println!("  r13={:#018x} r14={:#018x} r15={:#018x}", f.r13, f.r14, f.r15);
    crate::println!(
        "  cr0={:#x} cr2={:#x} cr3={:#x} cr4={:#x}",
        cpu::read_cr0(),
        cpu::read_cr2(),
        cpu::read_cr3(),
        cpu::read_cr4()
    );
}

fn exception(f: &mut TrapFrame) {
    let vec = f.vector as usize;
    crate::console::set_panicking();
    crate::println!();
    crate::println!("!!! CPU EXCEPTION {} ({}) error={:#x}", vec, EXCEPTION_NAMES[vec], f.error_code);
    if vec == 14 {
        let e = f.error_code;
        crate::println!(
            "  page fault at {:#x}: {} {} {}{}",
            cpu::read_cr2(),
            if e & 1 != 0 { "protection" } else { "not-present" },
            if e & 2 != 0 { "write" } else { "read" },
            if e & 4 != 0 { "user" } else { "kernel" },
            if e & 16 != 0 { " instruction-fetch" } else { "" }
        );
    }
    dump_frame(f);
    panic!("unrecoverable CPU exception");
}

#[no_mangle]
pub extern "sysv64" fn interrupt_dispatch(frame: *mut TrapFrame) {
    let f = unsafe { &mut *frame };
    let vec = f.vector as usize;
    if vec < 32 {
        exception(f);
        return;
    }
    if vec == VEC_SPURIOUS as usize {
        SPURIOUS_COUNT.fetch_add(1, Ordering::Relaxed);
        return; // no EOI for spurious interrupts
    }
    let h = HANDLERS[vec].load(Ordering::Acquire);
    if h != NO_HANDLER {
        let handler: Handler = unsafe { core::mem::transmute(h) };
        handler(f);
    } else {
        crate::println!("[irq] unhandled vector {}", vec);
    }
    apic::eoi();
}
